version: '3'
services:
  db:
    image: postgres:latest
    container_name: my_db_compose
    ports:
      - "55432:5432"
    environment:
      - POSTGRES_DB=Phonlawat
      - POSTGRES_USER=Phonlawat
      - POSTGRES_PASSWORD=Phonlawat

  app:
    image: prawee/strapi:latest
    container_name: my_app_compose
    ports:  
      - "8080:1337"
    environment:
      DATABASE_HOST: db   
      DATABASE_PORT: 5432 
      DATABASE_NAME: Phonlawat
      DATABASE_USERNAME: Phonlawat
      DATABASE_PASSWORD: Phonlawat
    depends_on:
      - db
